//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppCulture {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppCulture() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipesMVC.Resources.AppCulture", typeof(AppCulture).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you think there have been a problem, contact site manager, And ask for restrictions..
        /// </summary>
        public static string _403content {
            get {
                return ResourceManager.GetString("403content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 403 Unauthorvized.
        /// </summary>
        public static string _403title {
            get {
                return ResourceManager.GetString("403title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource cannot be found.&lt;br /&gt;If you think there have been a problem, contact site manager..
        /// </summary>
        public static string _404content {
            get {
                return ResourceManager.GetString("404content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Not Found.
        /// </summary>
        public static string _404title {
            get {
                return ResourceManager.GetString("404title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us: Contact Us, A little about us..
        /// </summary>
        public static string AboutUsTitleNav {
            get {
                return ResourceManager.GetString("AboutUsTitleNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page: overview and recommendations.
        /// </summary>
        public static string HomeTitleNav {
            get {
                return ResourceManager.GetString("HomeTitleNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string Recipes {
            get {
                return ResourceManager.GetString("Recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Recipies, Search Recipes.
        /// </summary>
        public static string RecipesTitleNav {
            get {
                return ResourceManager.GetString("RecipesTitleNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Managment.
        /// </summary>
        public static string SiteManagment {
            get {
                return ResourceManager.GetString("SiteManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Managment: Configuration, Users, And Recipes..
        /// </summary>
        public static string SiteManagmentTitleNav {
            get {
                return ResourceManager.GetString("SiteManagmentTitleNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name or Email.
        /// </summary>
        public static string UserNameEmailLogin {
            get {
                return ResourceManager.GetString("UserNameEmailLogin", resourceCulture);
            }
        }
    }
}
