//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesMVC.Models.EF_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Ratings = new HashSet<Rating>();
            this.Favorites = new HashSet<Favorite>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string RouteURL { get; set; }
        public string Title { get; set; }
        public string Ingredients { get; set; }
        public string Instructions { get; set; }
        public Nullable<double> AvgRating { get; set; }
        public Nullable<int> MainImage { get; set; }
        public Nullable<System.DateTime> UploadedAt { get; set; }
        public string Description { get; set; }
        public Nullable<System.TimeSpan> PrepTime { get; set; }
        public Nullable<System.TimeSpan> CookTime { get; set; }
        public Nullable<System.TimeSpan> TotalTime { get; set; }
        public Nullable<int> RecipeYield { get; set; }
        public string KeyWords { get; set; }
        public Nullable<bool> publicStatus { get; set; }
        public Nullable<int> TotalViews { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorites { get; set; }
    }
}
